Update progbar

diff --git a/progbar b/progbar
--- a/progbar
+++ b/progbar
@@ -1,8 +1,26 @@
 #!/usr/bin/env bash
-#Prog() { echo "scale=2; ${3:-100} * ($1 / $2)" | bc | cut -d\. -f1 ; }
+
+### from: dumpster-of-things/scripts/getSize
+shopt -s checkwinsize && (:;:) && declare -g COLUMNS LINES
+GetSize() {
+	local fn S
+	_1() { printf '%s %s\n' "${COLUMNS}" "${LINES}" ; }
+	_2() { read LINES COLUMNS < <(stty size ) ; (:;:) && printf '%s %s\n' "${COLUMNS}" "${LINES}" ; }
+	_3() { printf '%b' "${TMUX:+\\ePtmux;\\e}\\e[14t${TMUX:+\\e\\\\}" ; IFS=';t' read -d t -t 0.05 -sra term_size ; printf '%i %i\n' "$(( ${term_size[2]} / 16 ))" "$(( ${term_size[1]} / 8 ))" ; }
+	for fn in {1..3}; do
+		[[ ${S:="$(_${fn})"} == *[1-9]\ [1-9]* ]] && break || continue
+	done
+	echo "${S%\ *} ${S#*\ }" | cut -d\  -f${1:-1,2}
+}
+###
+
+### replaces: dumpster-of-things/scripts/prog[.go]
+Prog() { { echo "scale=2; ${3:-100} * ($1 / $2)" | bc | cut -d\. -f1 ; } || echo '0' ; }
+
 Bars() { printf "\e[0;30m\u256D\e[9m%${2}s\e[29m\u256E\n\u251D\e[1;9;32m%${1}s\e[2;34m%$((${2}-${1}))s\e[m\e[0;30m\u2525\n\u2570\e[9m%${2}s\e[29m\u256F\e[0m\n%${2}s${3}\n" ; }
-Spit() { w=$(($(getSize x)-4)) ; Bars $(prog $w $2 $1 | tr -d "%") $w "$(prog 100 $2 $1)%" ; }
-#Spit() { w=$(($(getSize x)-4)) ; Bars $(Prog $1 $2 $w) $w "$(Prog $1 $2)%%" ; }
+#Spit() { w=$(($(getSize x)-4)) ; Bars $(prog $1 $2 $w) $w "$(prog $1 $2)%%" ; }
+Spit() { w=$(($(GetSize 1)-4)) ; Bars $(Prog $1 $2 $w) $w "$(Prog $1 $2)%%" ; }
+
 if [[ "${1:-}${2:-}" != @([0-9])+([0-9]) ]]; then
 	[[ "${2:-$1}" != *(\-)[eE][xX][aA][mM][pP][lL][eE] ]] || { tput civis; i=1; for((;i<42;)){ tput clear ; Spit $((++i)) 42 ; sleep 0.1 ; }; tput reset ; exit 0 ; }
 	echo 'USAGE:'$'\n''   `progbar {current_count} {total}`'
@@ -15,9 +33,10 @@ if [[ "${1:-}${2:-}" != @([0-9])+([0-9]) ]]; then
 	echo '* You may want to extract the useful bits from this script and add them to your project directly as to eliminate unecessary overhead.'$'\n'
 	exit $(($#==0?1:0))
 else
-	Spit ${@} || {
-		[[ -x $(which prog) ]] || { echo "Missing dependency: https://github.com/dumpster-of-things/scripts/raw/main/prog" ; }
-		[[ -x $(which getSize) ]] || { echo "Missing dependency: https://github.com/dumpster-of-things/scripts/raw/main/getSize" ; }
-		exit 1
-	}	
+	#Spit ${@} || {
+	#	[[ -x $(which prog) ]] || { echo "Missing dependency: https://github.com/dumpster-of-things/scripts/raw/main/prog" ; }
+	#	[[ -x $(which getSize) ]] || { echo "Missing dependency: https://github.com/dumpster-of-things/scripts/raw/main/getSize" ; }
+	#	exit 1
+	#}
+	Spit ${@}
 fi
