Update progbar

diff --git a/progbar b/progbar
--- a/progbar
+++ b/progbar
@@ -1,11 +1,4 @@
 #!/usr/bin/env bash
-
-[[ -x $(which prog) ]] || { echo "Missing dependency: https://github.com/dumpster-of-things/scripts/raw/main/prog" ; exit 1 ; }
-[[ -x $(which getSize) ]] || { echo "Missing dependency:https://github.com/dumpster-of-things/scripts/raw/main/getSize" ; exit 1 ; }
-spitBar() { printf "\e[0;30m\u256D\e[9m%${2}s\e[29m\u256E\n\u251D\e[1;9;32m%${1}s\e[2;34m%$((${2}-${1}))s\e[m\e[0;30m\u2525\n\u2570\e[9m%${2}s\e[29m\u256F\e[0m\n%${2}s${3}\n" ; }
-
-[[ "${2:-$1}" != *(\-)[eE][xX][aA][mM][pP][lL][eE] ]] || { tput civis; i=1; for((;i<42;)){ tput clear ; spitBar $((++i)) 42 "$(prog 100 42 $i)%" ; sleep 0.1 ; }; tput reset ; exit 0 ; }
-
 [[ "$1" != *(\-)@([hH])?([eE][lL][pP]) ]] || {
 	echo 'USAGE:   progbar `{current_job_count} {total_jobs}`'
 	echo 'Generates a singe "frame" of a progress meter.'
@@ -15,7 +8,11 @@ spitBar() { printf "\e[0;30m\u256D\e[9m%${2}s\e[29m\u256E\n\u251D\e[1;9;32m%${1}
 	echo $'\n''* You may want to extract the useful bits from this script and add them to your project directly as to eliminate unecessary overhead.'
 	exit 0
 }
-
+[[ -x $(which prog) ]] || { echo "Missing dependency: https://github.com/dumpster-of-things/scripts/raw/main/prog" ; exit 1 ; }
+[[ -x $(which getSize) ]] || { echo "Missing dependency: https://github.com/dumpster-of-things/scripts/raw/main/getSize" ; exit 1 ; }
+Bars() { printf "\e[0;30m\u256D\e[9m%${2}s\e[29m\u256E\n\u251D\e[1;9;32m%${1}s\e[2;34m%$((${2}-${1}))s\e[m\e[0;30m\u2525\n\u2570\e[9m%${2}s\e[29m\u256F\e[0m\n%${2}s${3}\n" ; }
+Spit() { Bars $(prog $(($(getSize x)-4)) $2 $1 | tr -d \%) $(($(getSize x)-4)) "$(prog 100 $2 $1)%" ; }
+[[ "${2:-$1}" != *(\-)[eE][xX][aA][mM][pP][lL][eE] ]] || { tput civis; i=1; for((;i<42;)){ tput clear ; Spit $((++i)) 42 ; sleep 0.1 ; }; tput reset ; exit 0 ; }
 (($#==2)) || { echo 'Two numerical arguments required.' ; exit 1 ; }
-#(($1>$2)) || spitBar $1 $2 "$(prog 100 $2 $1)%"
-spitBar $(prog $(($(getSize x)-4)) $2 $1 | tr -d \%) $(($(getSize x)-4)) "$(prog 100 $2 $1)%"
+
+Spit ${@}
